name: nn_env
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.12
    - pip
    - gensim
    - pytorch=2.8.0
    - transformers
    - h5py
    - torchinfo
    - tqdm
    - numpy
    - pandas
    - scikit-learn
    - seaborn
    - matplotlib
    - jupyterlab
    - mlflow
    - lightning
    - optuna
    - tensorboard