name: nn_env
channels:
    - defaults
    - pytorch-nightly
    - conda-forge
dependencies:
    - python=3.12
    - pip
    - gensim
    - pytorch # pytorch-cpu for cpu-only 
    - numpy
    - pandas
    - scikit-learn
    - torchinfo
    - seaborn
    - matplotlib
    - seaborn
    - jupyterlab
    - mlflow
