name: nn_env
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.13
    - pip
    # - pytorch # complete installation 
    - pytorch-cpu=2.8 # for cpu-only 
    - lightning
    - transformers
    - datasets
    - torchvision
    - numpy
    - pandas
    - scikit-learn
    - torchinfo
    - matplotlib
    - seaborn
    - jupyterlab
    - mlflow
    - optuna

